# Generated by Django 2.2.3 on 2019-10-09 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectFormular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_panel_num', models.CharField(blank=True, max_length=50, verbose_name='Номер пульта')),
                ('ppk_model', models.CharField(blank=True, max_length=50, verbose_name='Модель ППК')),
                ('ppk_num', models.CharField(blank=True, max_length=50, verbose_name='Номер ППК')),
                ('object_floor', models.PositiveIntegerField(blank=True, verbose_name='Этаж')),
                ('max_floor', models.PositiveIntegerField(blank=True, verbose_name='Этажность')),
                ('porch_num', models.PositiveIntegerField(blank=True, verbose_name='Подъезд')),
                ('has_animals_flg', models.BooleanField(default=False, verbose_name='Есть животные')),
                ('has_concierge_flg', models.BooleanField(default=False, verbose_name='Есть консьерж')),
                ('has_intercom_flg', models.BooleanField(default=False, verbose_name='Есть домофон')),
                ('has_code_doors_flg', models.BooleanField(default=False, verbose_name='Есть кодовые двери')),
                ('has_windows_gratings_flg', models.BooleanField(default=False, verbose_name='Есть решетки на окнах')),
                ('has_double_doors_flg', models.BooleanField(default=False, verbose_name='Есть двойные двери')),
                ('has_keys_flg', models.BooleanField(default=False, verbose_name='Есть ключи')),
                ('rooms_num', models.PositiveIntegerField(blank=True, verbose_name='Кол-во помещений')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mounter_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_objformular', to=settings.AUTH_USER_MODEL, verbose_name='Монтажор')),
            ],
            options={
                'ordering': ('control_panel_num',),
            },
        ),
    ]
