# Generated by Django 2.2.3 on 2019-10-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_status', '0003_servicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
            ],
        ),
    ]
