# Generated by Django 2.2.3 on 2019-10-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_status', '0005_maincontractors_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontractors',
            name='contractor',
            field=models.CharField(max_length=250, verbose_name='Тип объекта'),
        ),
    ]
