# Generated by Django 2.2.3 on 2019-10-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_status', '0006_auto_20191004_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(max_length=50, verbose_name='Тип клиента')),
            ],
        ),
    ]
