# Generated by Django 2.2.3 on 2019-10-09 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('object', '0001_initial'),
        ('project_status', '0009_auto_20191008_1558'),
        ('payment_conditions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0004_auto_20191008_2256'),
        ('mounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_by_project', to='client.Client')),
                ('last_upd_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_by_lastupd', to=settings.AUTH_USER_MODEL)),
                ('manager_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_by_projectmanager', to=settings.AUTH_USER_MODEL)),
                ('mounting_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mounting_by_project', to='mounting.Mounting')),
                ('object_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_by_project', to='object.Object')),
                ('owner_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_by_projectowner', to=settings.AUTH_USER_MODEL)),
                ('payment_conditions_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentconditions_by_project', to='payment_conditions.PaymentConditions')),
                ('service_type_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_by_project', to='project_status.ServiceType')),
                ('status_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_by_project', to='project_status.ProjectStatus')),
            ],
            options={
                'ordering': ('client_id',),
            },
        ),
    ]
