# Generated by Django 2.2.3 on 2019-10-09 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_status', '0009_auto_20191008_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mounting', models.CharField(default='Монтаж', max_length=50, verbose_name='Монтаж')),
                ('object_inspection', models.BooleanField(default=False, verbose_name='Осмотр объекта')),
                ('estimate', models.PositiveIntegerField(blank=True, verbose_name='Смета')),
                ('mounting_value', models.PositiveIntegerField(blank=True, verbose_name='Сумма за монтаж')),
                ('mounting_income', models.PositiveIntegerField(blank=True, verbose_name='Доход от монтажа')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contractor_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_by_mounting', to='project_status.MainContractors', verbose_name='Компания на монтаж')),
                ('payment_type_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_by_mounting', to='project_status.PaymentType', verbose_name='Способ оплаты')),
            ],
            options={
                'ordering': ('mounting_income',),
            },
        ),
    ]
