# Generated by Django 2.2.3 on 2019-10-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_status', '0007_clienttype'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Пасспорт')),
                ('channel', models.CharField(blank=True, max_length=200, verbose_name='Отчество')),
                ('referal_program', models.CharField(blank=True, max_length=200, verbose_name='Фамилия')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Улица')),
                ('house_num', models.PositiveIntegerField(blank=True, verbose_name='Номер дома')),
                ('flat_num', models.PositiveIntegerField(blank=True, verbose_name='Номер квартиры')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=200, verbose_name='Емейл')),
                ('tax_number', models.CharField(blank=True, max_length=10, verbose_name='ЕГРПО')),
                ('network_cl_5plus', models.BooleanField(default=False, verbose_name='ЕГРПО')),
                ('network_cl_20plus', models.BooleanField(default=False, verbose_name='ЕГРПО')),
                ('balance_1c', models.IntegerField(blank=True, verbose_name='Номер дома')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='project_status.ClientType')),
                ('contact_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='contact.Contact')),
            ],
            options={
                'ordering': ('company_name',),
            },
        ),
    ]
