# Generated by Django 2.2.3 on 2019-10-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('project_status', '0009_auto_20191008_1558'),
        ('client', '0002_auto_20191008_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Улица')),
                ('house_num', models.PositiveIntegerField(blank=True, verbose_name='Номер дома')),
                ('flat_num', models.PositiveIntegerField(blank=True, verbose_name='Номер квартиры')),
                ('date_first_reation', models.DateField(blank=True, verbose_name='Дата первой реакции')),
                ('denying_password', models.CharField(db_index=True, max_length=200, verbose_name='Пароль подтверждения отмены')),
                ('additional_services', models.CharField(db_index=True, max_length=200, verbose_name='Дополнительные сервисы')),
                ('scan_main_deal', models.ImageField(blank=True, upload_to='main_deals/', verbose_name='Скан основного договора')),
                ('scan_mounting_deal', models.ImageField(blank=True, upload_to='mounting_deals/', verbose_name='Скан монтажного договора')),
                ('verified_deal_flg', models.BooleanField(default=False, verbose_name='Флаг подтверждения договора')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_by_client', to='client.Client', verbose_name='Клиент')),
                ('object_type_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_by_type', to='project_status.ObjectType', verbose_name='Тип обьекта')),
                ('property_type_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_by_property', to='project_status.PropertyType', verbose_name='Тип собственности')),
                ('rel_person1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_by_contact1', to='contact.Contact', verbose_name='Связанное лицо1')),
                ('rel_person2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_by_contact2', to='contact.Contact', verbose_name='Связанное лицо2')),
                ('rel_person3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_by_contact3', to='contact.Contact', verbose_name='Связанное лицо3')),
                ('rel_person4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_by_contact4', to='contact.Contact', verbose_name='Связанное лицо4')),
            ],
            options={
                'ordering': ('street',),
            },
        ),
    ]
