# Generated by Django 2.2.3 on 2019-10-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_status', '0009_auto_20191008_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_liability', models.PositiveIntegerField(blank=True, verbose_name='Материальная ответственность')),
                ('base_payment', models.PositiveIntegerField(blank=True, verbose_name='Базовая оплата')),
                ('extra_departure_value', models.PositiveIntegerField(blank=True, verbose_name='Стоимость дополнительного выезда')),
                ('engeneer_ts_value', models.PositiveIntegerField(blank=True, verbose_name='Стоимость ТО инженера')),
                ('sms_notification_value', models.PositiveIntegerField(blank=True, verbose_name='Стоимость СМС опопвещения')),
                ('additional_channel_value', models.PositiveIntegerField(blank=True, verbose_name='Стоимость доп. канала связи')),
                ('stayhome_value', models.PositiveIntegerField(blank=True, verbose_name='Стоимость услуги Остаюсь дома')),
                ('extra_ensurance_value', models.PositiveIntegerField(blank=True, verbose_name='Стоимость доп. страховки')),
                ('extra_detector_value', models.PositiveIntegerField(blank=True, verbose_name='Стоимость доп. датчика')),
                ('operation_mode_value', models.PositiveIntegerField(blank=True, verbose_name='Стоимость Режим работы объекта')),
                ('monthly_report_value', models.PositiveIntegerField(blank=True, verbose_name='Стоимость месячного отчета')),
                ('alarm_button_value', models.PositiveIntegerField(blank=True, verbose_name='Стоимость Тревожной кнопки')),
                ('duress_code_value', models.PositiveIntegerField(blank=True, verbose_name='Стоимость Код под принуждением')),
                ('liqpay_subsription', models.BooleanField(default=False, verbose_name='Подписка liqpay')),
                ('liqpay_subsription_date', models.DateField(blank=True, verbose_name='Начало подписки liqpay')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_payment_conditions', to='project_status.PaymentType', verbose_name='Способ оплаты')),
            ],
            options={
                'ordering': ('base_payment',),
            },
        ),
    ]
